-- MySQL Script generated by MySQL Workbench
-- Fri Oct  5 16:35:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`deporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deporte` (
  `iddeporte` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `discontinuado` TINYINT NULL,
  PRIMARY KEY (`iddeporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insumo` (
  `idinsumo` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `stock` SMALLINT(2) NOT NULL,
  `precio` FLOAT NOT NULL,
  `deporte_iddeporte` INT NOT NULL AUTO_INCREMENT,
  `discontinuado` TINYINT NULL,
  PRIMARY KEY (`idinsumo`),
  INDEX `fk_insumo_deporte_idx` (`deporte_iddeporte` ASC),
  CONSTRAINT `fk_insumo_deporte`
    FOREIGN KEY (`deporte_iddeporte`)
    REFERENCES `mydb`.`deporte` (`iddeporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cancha` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cancha` (
  `idcancha` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  `deporte_iddeporte` INT NOT NULL,
  `discontinuado` TINYINT NULL,
  PRIMARY KEY (`idcancha`),
  INDEX `fk_cancha_deporte_idx` (`deporte_iddeporte` ASC),
  CONSTRAINT `fk_cancha_deporte`
    FOREIGN KEY (`deporte_iddeporte`)
    REFERENCES `mydb`.`deporte` (`iddeporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idreserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `dni` VARCHAR(45) NULL,
  `esAdmin` BIT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `discontinuado` TINYINT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actividad` (
  `idactividad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `precio` FLOAT NOT NULL,
  `cancha_idcancha` INT NOT NULL,
  `discontinuada` TINYINT NULL,
  PRIMARY KEY (`idactividad`),
  INDEX `fk_actividad_cancha_idx` (`cancha_idcancha` ASC),
  CONSTRAINT `fk_actividad_cancha`
    FOREIGN KEY (`cancha_idcancha`)
    REFERENCES `mydb`.`cancha` (`idcancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inscripcion` (
  `idinscripcion` INT NOT NULL AUTO_INCREMENT,
  `fecha_alta` DATE NOT NULL,
  `fecha_baja` DATE NULL,
  `usuario_idpersona` INT NOT NULL,
  `actividad_idactividad` INT NOT NULL,
  PRIMARY KEY (`idinscripcion`),
  INDEX `fk_inscripcion_usuario_idx` (`usuario_idpersona` ASC),
  INDEX `fk_inscripcion_actividad_idx` (`actividad_idactividad` ASC),
  CONSTRAINT `fk_inscripcion_usuario`
    FOREIGN KEY (`usuario_idpersona`)
    REFERENCES `mydb`.`usuario` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_actividad`
    FOREIGN KEY (`actividad_idactividad`)
    REFERENCES `mydb`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horario_de_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`horario_de_actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`horario_de_actividad` (
  `idhorario_de_actividad` INT NOT NULL AUTO_INCREMENT,
  `dia` DATE NULL,
  `hora_inicio` VARCHAR(45) NULL,
  `hora_fin` VARCHAR(45) NULL,
  `actividad_idactividad` INT NOT NULL,
  PRIMARY KEY (`idhorario_de_actividad`),
  INDEX `fk_horario_de_actividad_actividad_idx` (`actividad_idactividad` ASC),
  CONSTRAINT `fk_horario_de_actividad_actividad`
    FOREIGN KEY (`actividad_idactividad`)
    REFERENCES `mydb`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`caja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`caja` (
  `idcaja` INT NOT NULL AUTO_INCREMENT,
  `monto_inicial` FLOAT NOT NULL,
  `fecha_apertura` DATE NOT NULL,
  `hora_apertura` TIME NOT NULL,
  `monto_final` INT NULL,
  `fecha_cierre` DATE NULL,
  `hora_cierre` TIME NULL,
  `usuario_idpersona` INT NOT NULL,
  PRIMARY KEY (`idcaja`),
  INDEX `fk_caja_usuario_idx` (`usuario_idpersona` ASC),
  CONSTRAINT `fk_caja_usuario`
    FOREIGN KEY (`usuario_idpersona`)
    REFERENCES `mydb`.`usuario` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comprobante_cfg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comprobante_cfg` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comprobante_cfg` (
  `idcomprobantecfg` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(3) NOT NULL,
  `prefijo` INT NULL,
  `numero_inicial` INT NULL,
  `ultimo_numero` INT NULL,
  `discontinuado` TINYINT NULL,
  PRIMARY KEY (`idcomprobantecfg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingreso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `importe` FLOAT NULL,
  `fecha` DATE NULL,
  `numero` INT NULL,
  `caja_idcaja` INT NOT NULL,
  `comprobante_cfg_idcomprobantecfg` INT NOT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_ingreso_caja_idx` (`caja_idcaja` ASC),
  INDEX `fk_ingreso_comprobante_cfg1_idx` (`comprobante_cfg_idcomprobantecfg` ASC),
  CONSTRAINT `fk_ingreso_caja`
    FOREIGN KEY (`caja_idcaja`)
    REFERENCES `mydb`.`caja` (`idcaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_comprobante_cfg1`
    FOREIGN KEY (`comprobante_cfg_idcomprobantecfg`)
    REFERENCES `mydb`.`comprobante_cfg` (`idcomprobantecfg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cuota` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cuota` (
  `idcuota` INT NOT NULL AUTO_INCREMENT,
  `numero_cuota` INT NULL,
  `ingreso_idingreso` INT NOT NULL,
  `inscripcion_idinscripcion` INT NOT NULL,
  PRIMARY KEY (`idcuota`),
  INDEX `fk_cuota_ingreso_idx` (`ingreso_idingreso` ASC),
  INDEX `fk_cuota_inscripcion_idx` (`inscripcion_idinscripcion` ASC),
  CONSTRAINT `fk_cuota_ingreso`
    FOREIGN KEY (`ingreso_idingreso`)
    REFERENCES `mydb`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuota_inscripcion`
    FOREIGN KEY (`inscripcion_idinscripcion`)
    REFERENCES `mydb`.`inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`egreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`egreso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`egreso` (
  `idegreso` INT NOT NULL AUTO_INCREMENT,
  `importe` FLOAT NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `caja_idcaja` INT NOT NULL,
  PRIMARY KEY (`idegreso`),
  INDEX `fk_egreso_caja_idx` (`caja_idcaja` ASC),
  CONSTRAINT `fk_egreso_caja`
    FOREIGN KEY (`caja_idcaja`)
    REFERENCES `mydb`.`caja` (`idcaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumo_por_reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insumo_por_reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insumo_por_reserva` (
  `insumo_idinsumo` INT NOT NULL,
  `reserva_idreserva` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`insumo_idinsumo`, `reserva_idreserva`),
  INDEX `fk_insumo_por_reserva_reserva_idx` (`reserva_idreserva` ASC),
  INDEX `fk_insumo_por_reserva_insumo_idx` (`insumo_idinsumo` ASC),
  CONSTRAINT `fk_insumo_por_reserva_insumo`
    FOREIGN KEY (`insumo_idinsumo`)
    REFERENCES `mydb`.`insumo` (`idinsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumo_por_reserva_reserva`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `mydb`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingreso_por_reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingreso_por_reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingreso_por_reserva` (
  `ingreso_idingreso` INT NOT NULL,
  `reserva_idreserva` INT NOT NULL,
  PRIMARY KEY (`ingreso_idingreso`, `reserva_idreserva`),
  INDEX `fk_ingreso_por_reserva_reserva_idx` (`reserva_idreserva` ASC),
  INDEX `fk_ingreso_por_reserva_ingreso_idx` (`ingreso_idingreso` ASC),
  CONSTRAINT `fk_ingreso_has_reserva_ingreso1`
    FOREIGN KEY (`ingreso_idingreso`)
    REFERENCES `mydb`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_has_reserva_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `mydb`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
