-- MySQL Script generated by MySQL Workbench
-- Tue Sep 25 14:27:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insumo` (
  `idinsumo` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `cantidad` SMALLINT(2) NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`idinsumo`, `categoria_idcategoria`),
  INDEX `fk_insumo_categoria_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_insumo_categoria`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cancha` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cancha` (
  `idcancha` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idcancha`, `categoria_idcategoria`),
  INDEX `fk_cancha_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_cancha_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idpersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `dni` VARCHAR(45) NULL,
  `esAdmin` BIT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`caja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`caja` (
  `idcaja` INT NOT NULL AUTO_INCREMENT,
  `monto` FLOAT NOT NULL,
  `fecha_apertura` DATE NOT NULL,
  `hora_apertura` TIME NOT NULL,
  `fecha_cierre` DATE NULL,
  `hora_cierre` TIME NULL,
  `usuario_idpersona` INT NOT NULL,
  PRIMARY KEY (`idcaja`),
  INDEX `fk_caja_usuario1_idx` (`usuario_idpersona` ASC),
  CONSTRAINT `fk_caja_usuario1`
    FOREIGN KEY (`usuario_idpersona`)
    REFERENCES `mydb`.`usuario` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cobro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cobro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cobro` (
  `idcobro` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `importe` FLOAT NULL,
  `operacion` TINYINT(1) NULL,
  `caja_idcaja` INT NOT NULL,
  PRIMARY KEY (`idcobro`, `caja_idcaja`),
  INDEX `fk_cobro_caja1_idx` (`caja_idcaja` ASC),
  CONSTRAINT `fk_cobro_caja1`
    FOREIGN KEY (`caja_idcaja`)
    REFERENCES `mydb`.`caja` (`idcaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `idreserva` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `adelanto` VARCHAR(45) NULL,
  `cancha_idcancha` INT NOT NULL,
  `cancha_categoria_idcategoria` INT NOT NULL,
  `cobro_idcobro` INT NOT NULL,
  PRIMARY KEY (`idreserva`, `cancha_idcancha`, `cancha_categoria_idcategoria`),
  INDEX `fk_reserva_cancha1_idx` (`cancha_idcancha` ASC, `cancha_categoria_idcategoria` ASC),
  INDEX `fk_reserva_cobro1_idx` (`cobro_idcobro` ASC),
  CONSTRAINT `fk_reserva_cancha1`
    FOREIGN KEY (`cancha_idcancha` , `cancha_categoria_idcategoria`)
    REFERENCES `mydb`.`cancha` (`idcancha` , `categoria_idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cobro1`
    FOREIGN KEY (`cobro_idcobro`)
    REFERENCES `mydb`.`cobro` (`idcobro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumo_x_reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insumo_x_reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insumo_x_reserva` (
  `insumo_idinsumo` INT NOT NULL,
  `insumo_categoria_idcategoria` INT NOT NULL,
  `reserva_idreserva` INT NOT NULL,
  `cantidad` TINYINT(2) NULL,
  `insumo_x_reservacol` VARCHAR(45) NULL,
  PRIMARY KEY (`insumo_idinsumo`, `insumo_categoria_idcategoria`, `reserva_idreserva`),
  INDEX `fk_insumo_has_reserva_reserva1_idx` (`reserva_idreserva` ASC),
  INDEX `fk_insumo_has_reserva_insumo1_idx` (`insumo_idinsumo` ASC, `insumo_categoria_idcategoria` ASC),
  CONSTRAINT `fk_insumo_has_reserva_insumo1`
    FOREIGN KEY (`insumo_idinsumo` , `insumo_categoria_idcategoria`)
    REFERENCES `mydb`.`insumo` (`idinsumo` , `categoria_idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumo_has_reserva_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `mydb`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actividad` (
  `idactividad` INT NOT NULL,
  `cancha_idcancha` INT NOT NULL,
  `cancha_categoria_idcategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`idactividad`, `cancha_idcancha`, `cancha_categoria_idcategoria`),
  INDEX `fk_actividad_cancha1_idx` (`cancha_idcancha` ASC, `cancha_categoria_idcategoria` ASC),
  CONSTRAINT `fk_actividad_cancha1`
    FOREIGN KEY (`cancha_idcancha` , `cancha_categoria_idcategoria`)
    REFERENCES `mydb`.`cancha` (`idcancha` , `categoria_idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inscripcion` (
  `idinscripcion` INT NOT NULL,
  `actividad_idactividad` INT NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `fecha_baja` DATE NULL,
  `usuario_idpersona` INT NOT NULL,
  PRIMARY KEY (`idinscripcion`, `actividad_idactividad`),
  INDEX `fk_actividad_has_socio_actividad1_idx` (`actividad_idactividad` ASC),
  INDEX `fk_inscripcion_usuario1_idx` (`usuario_idpersona` ASC),
  CONSTRAINT `fk_actividad_has_socio_actividad1`
    FOREIGN KEY (`actividad_idactividad`)
    REFERENCES `mydb`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_usuario1`
    FOREIGN KEY (`usuario_idpersona`)
    REFERENCES `mydb`.`usuario` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horario_de_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`horario_de_actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`horario_de_actividad` (
  `idhorario_de_actividad` INT NOT NULL,
  `dia` DATE NULL,
  `hora_inicio` VARCHAR(45) NULL,
  `hora_fin` VARCHAR(45) NULL,
  `actividad_idactividad` INT NOT NULL,
  `actividad_cancha_idcancha` INT NOT NULL,
  `actividad_cancha_categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idhorario_de_actividad`, `actividad_idactividad`, `actividad_cancha_idcancha`, `actividad_cancha_categoria_idcategoria`),
  INDEX `fk_horario_de_actividad_actividad1_idx` (`actividad_idactividad` ASC, `actividad_cancha_idcancha` ASC, `actividad_cancha_categoria_idcategoria` ASC),
  CONSTRAINT `fk_horario_de_actividad_actividad1`
    FOREIGN KEY (`actividad_idactividad` , `actividad_cancha_idcancha` , `actividad_cancha_categoria_idcategoria`)
    REFERENCES `mydb`.`actividad` (`idactividad` , `cancha_idcancha` , `cancha_categoria_idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cuota` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cuota` (
  `idcuota` INT NOT NULL,
  `inscripcion_idinscripcion` INT NOT NULL,
  `numero_cuota` INT NULL,
  `cobro_idcobro` INT NOT NULL,
  PRIMARY KEY (`idcuota`, `inscripcion_idinscripcion`),
  INDEX `fk_cuota_inscripcion1_idx` (`inscripcion_idinscripcion` ASC),
  INDEX `fk_cuota_cobro1_idx` (`cobro_idcobro` ASC),
  CONSTRAINT `fk_cuota_inscripcion1`
    FOREIGN KEY (`inscripcion_idinscripcion`)
    REFERENCES `mydb`.`inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuota_cobro1`
    FOREIGN KEY (`cobro_idcobro`)
    REFERENCES `mydb`.`cobro` (`idcobro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
